name: "Test action-install-pulumi-cli"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  latest:
    name: Test Latest Version Install
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile --ignore-optional
      - run: yarn package
      - uses: ./
      - run: pulumi version
  specific:
    name: Test Specific Version Install
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile --ignore-optional
      - run: yarn package
      - uses: ./
        with:
          pulumi-version: 2.14.0
      - run: pulumi version
  range:
    name: Test Range Version Install
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile --ignore-optional
      - run: yarn package
      - uses: ./
        with:
          pulumi-version: 3.0.*
      - run: pulumi version
